/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto;

import javax.swing.JOptionPane;
import static projeto.Projeto.contador;
import static projeto.Projeto.contadorCaminhao;
import static projeto.Projeto.contadorCaminhao2;
import static projeto.Projeto.contadorCarro;
import static projeto.Projeto.contadorCarro2;
import static projeto.Projeto.contadorMoto;
import static projeto.Projeto.contadorMoto2;
import static projeto.Tela1.xusuario;
import static projeto.Tela2.xcaminhoes;
import static projeto.Tela2.xcarros;
import static projeto.Tela2.xmotos;
import static projeto.Tela3.xcelulares;
import static projeto.Tela3.xeletrodomesticos;
import static projeto.Tela3.xnotebooks;

/**
 *
 * @author bielc
 */
public class Tela7 extends javax.swing.JFrame {

    /**
     * Creates new form Tela7
     */
    public Tela7() {
        initComponents();
    }
    
    int indicador = -1;
    int indicador2;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UP SEGUROS");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 546, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel3.setText("EDIÇÃO DE DADOS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, 20));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 150, -1));

        jLabel2.setText("DIGITE O CPF");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        jLabel4.setText("NOME:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jTextField2.setEditable(false);
        jTextField2.setToolTipText("");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 210, -1));

        jLabel5.setText("CPF:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jTextField3.setEditable(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 210, -1));

        jLabel6.setText("IDADE:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel7.setText("TELEFONE:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jTextField4.setEditable(false);
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 210, -1));

        jLabel8.setText("ENFEREÇO:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jTextField5.setEditable(false);
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 210, -1));

        jLabel9.setText("MODELO:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        jLabel10.setText("PLACA:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));

        jLabel11.setText("CHASSI:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

        jLabel12.setText("COR:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        jLabel13.setText("PREÇO:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));

        jTextField11.setEditable(false);
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 210, -1));

        jTextField12.setEditable(false);
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 210, -1));

        jTextField13.setEditable(false);
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 210, -1));

        jTextField14.setEditable(false);
        getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 210, -1));

        jTextField15.setEditable(false);
        getContentPane().add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 210, -1));

        jTextField6.setEditable(false);
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 210, -1));

        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, -1));

        jButton2.setText("ALTERAR DADOS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 150, 30));

        jButton3.setText("Voltar para tela anterior");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 160, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed

    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        indicador = -1;
        
        String cpf = jTextField1.getText();

        for(int x = 0;x<xusuario.size();x++){
            if(xusuario.get(x).getCpf().equals(cpf)){
                indicador = x;
            }
        }
        
        if(indicador == -1){
            JOptionPane.showMessageDialog(null,"CPF NAO ENCONTRADO");
                        jTextField2.setText("");
                        jTextField3.setText("");
                        jTextField6.setText("");
                        jTextField4.setText("");
                        jTextField5.setText("");
                        jTextField11.setText("");
                        jTextField12.setText("");
                        jTextField13.setText("");
                        jTextField14.setText("");
                        jTextField15.setText("");
        } 
            
                        jTextField2.setText(xusuario.get(indicador).getNome());
                        jTextField3.setText(xusuario.get(indicador).getCpf());
                        jTextField6.setText(xusuario.get(indicador).getIdade());
                        jTextField4.setText(xusuario.get(indicador).getTelefone());
                        jTextField5.setText(xusuario.get(indicador).getEndereco());
        
        
            if (xusuario.get(indicador).getPk() == 1){
                for(int i = 0;i<xcarros.size();i++){
                    if(xcarros.get(i).getPkx() == indicador){
                        indicador2 = i;
                        jTextField11.setText(xcarros.get(i).getModelo());
                        jTextField12.setText(xcarros.get(i).getPlaca());
                        jTextField13.setText(xcarros.get(i).getChassi());
                        jTextField14.setText(xcarros.get(i).getCor());
                        jTextField15.setText(xcarros.get(i).getPreco());
                    }
                }  
            }  else if(xusuario.get(indicador).getPk() == 2){
                for(int i = 0;i<xmotos.size();i++){
                    if(xmotos.get(i).getPkx() == indicador){
                        indicador2 = i;
                        jTextField11.setText(xmotos.get(i).getModelo());
                        jTextField12.setText(xmotos.get(i).getPlaca());
                        jTextField13.setText(xmotos.get(i).getChassi());
                        jTextField14.setText(xmotos.get(i).getCor());
                        jTextField15.setText(xmotos.get(i).getPreco());
                    }
                }  
            }  else if(xusuario.get(indicador).getPk() == 3){
                for(int i = 0;i<xcaminhoes.size();i++){
                    if(xcaminhoes.get(i).getPkx() == indicador){
                        indicador2 = i;
                        jTextField11.setText(xcaminhoes.get(i).getModelo());
                        jTextField12.setText(xcaminhoes.get(i).getPlaca());
                        jTextField13.setText(xcaminhoes.get(i).getChassi());
                        jTextField14.setText(xcaminhoes.get(i).getCor());
                        jTextField15.setText(xcaminhoes.get(i).getPreco());
                    }
                } 
            }   
            
            if (xusuario.get(indicador).getPk() == 4){
                for(int i = 0;i<xcelulares.size();i++){
                    if(xcelulares.get(i).getPkx() == indicador){
                        indicador2 = i;
                        jTextField11.setText(xcelulares.get(i).getModelo());
                        jTextField12.setText(xcelulares.get(i).getNf());
                        jTextField13.setText(xcelulares.get(i).getId());
                        jTextField14.setText(xcelulares.get(i).getCor());
                        jTextField15.setText(xcelulares.get(i).getPreco());
                    }
                }  
            }  else if(xusuario.get(indicador).getPk() == 5){
                for(int i = 0;i<xeletrodomesticos.size();i++){
                    if(xeletrodomesticos.get(i).getPkx() == indicador){
                        indicador2 = i;
                        jTextField11.setText(xeletrodomesticos.get(i).getModelo());
                        jTextField12.setText(xeletrodomesticos.get(i).getNf());
                        jTextField13.setText(xeletrodomesticos.get(i).getId());
                        jTextField14.setText(xeletrodomesticos.get(i).getCor());
                        jTextField15.setText(xeletrodomesticos.get(i).getPreco());
                    }
                }  
            }  else if(xusuario.get(indicador).getPk() == 6){
                for(int i = 0;i<xnotebooks.size();i++){
                    if(xnotebooks.get(i).getPkx() == indicador){
                        indicador2 = i;
                        jTextField11.setText(xnotebooks.get(i).getModelo());
                        jTextField12.setText(xnotebooks.get(i).getNf());
                        jTextField13.setText(xnotebooks.get(i).getId());
                        jTextField14.setText(xnotebooks.get(i).getCor());
                        jTextField15.setText(xnotebooks.get(i).getPreco());
                    }
                } 
            }
            
            jTextField2.setEditable(true);
            jTextField3.setEditable(true);
            jTextField6.setEditable(true);
            jTextField4.setEditable(true);
            jTextField5.setEditable(true);
            jTextField11.setEditable(true);
            jTextField12.setEditable(true);
            jTextField13.setEditable(true);
            jTextField14.setEditable(true);
            jTextField15.setEditable(true);
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         
        xusuario.get(indicador).setNome(jTextField2.getText());
        xusuario.get(indicador).setCpf(jTextField3.getText());
        xusuario.get(indicador).setIdade(jTextField6.getText());
        xusuario.get(indicador).setTelefone(jTextField4.getText());
        xusuario.get(indicador).setEndereco(jTextField5.getText());
        
        if(xusuario.get(indicador2).getPk() == 1){ 
        xcarros.get(indicador2).setModelo(jTextField11.getText());
        xcarros.get(indicador2).setPreco(jTextField12.getText());
        xcarros.get(indicador2).setCor(jTextField13.getText());
        xcarros.get(indicador2).setPlaca(jTextField14.getText());
        xcarros.get(indicador2).setChassi(jTextField15.getText());

        } else if(xusuario.get(indicador).getPk() == 2){
            xmotos.get(indicador2).setModelo(jTextField11.getText());
            xmotos.get(indicador2).setPreco(jTextField12.getText());
            xmotos.get(indicador2).setCor(jTextField13.getText());
            xmotos.get(indicador2).setPlaca(jTextField14.getText());
            xmotos.get(indicador2).setChassi(jTextField15.getText());
            
        } else if(xusuario.get(indicador).getPk() == 3){
            xcaminhoes.get(indicador2).setModelo(jTextField11.getText());
            xcaminhoes.get(indicador2).setPreco(jTextField12.getText());
            xcaminhoes.get(indicador2).setCor(jTextField13.getText());
            xcaminhoes.get(indicador2).setPlaca(jTextField14.getText());
            xcaminhoes.get(indicador2).setChassi(jTextField15.getText());
            
        }  else if(xusuario.get(indicador).getPk() == 4){
            xcelulares.get(indicador2).setModelo(jTextField11.getText());
            xcelulares.get(indicador2).setPreco(jTextField12.getText());
            xcelulares.get(indicador2).setCor(jTextField13.getText());
            xcelulares.get(indicador2).setNf(jTextField14.getText());
            xcelulares.get(indicador2).setId(jTextField15.getText());
            
        }  else if(xusuario.get(indicador).getPk() == 5){
            xeletrodomesticos.get(indicador2).setModelo(jTextField11.getText());
            xeletrodomesticos.get(indicador2).setPreco(jTextField12.getText());
            xeletrodomesticos.get(indicador2).setCor(jTextField13.getText());
            xeletrodomesticos.get(indicador2).setNf(jTextField14.getText());
            xeletrodomesticos.get(indicador2).setId(jTextField15.getText());
            
        }  else if(xusuario.get(indicador).getPk() == 6){
            xnotebooks.get(indicador2).setModelo(jTextField11.getText());
            xnotebooks.get(indicador2).setPreco(jTextField12.getText());
            xnotebooks.get(indicador2).setCor(jTextField13.getText());
            xnotebooks.get(indicador2).setNf(jTextField14.getText());
            xnotebooks.get(indicador2).setId(jTextField15.getText());
        } 
        
        JOptionPane.showMessageDialog(null,"DADOS ALTERADOS COM SUCESSO");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setVisible(false);
        Tela6 tela6 = new Tela6();
        tela6.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
